spring.application.name=vote-api

spring.datasource.url=jdbc:postgresql://localhost:5432/voteApi
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enable=true


